spring:
    application:
        name: zod
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=zod-app;encrypt=true;trustServerCertificate=true
        username: sa
        password: thssla1!@
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false

security:
    jwt:
        secret: ${JWT_SECRET:JffuxoG0ZivcKkw/nKTNn4RomIIv4/NVgrxZmN3hpXfXznfqGGuECDOaChKuqV6LXTdiUE/PCZrvskhYaacSVw==}
        access-mins: 30
        refresh-mins: 60
