spring:
    application:
        name: zod
    config:
        import: application-dev.yml
    main:
        web-application-type: servlet
    thymeleaf:
        cache: false
        check-template-location: false
        encoding: UTF-8
        mode: HTML
server:
    port: 18080
    servlet:
        context-path: /
security:
    jwt:
        secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
        access: 900
        refresh: 1209600
